### ISSUE TITLE
Printing mistake - spelling mistake

### ISSUE THREAD

**Issue by osama0802** [PacktPublishing/Web-API-Development-with-ASP.NET-Core-8#1]
Page number - 20 
Under the heading - What is an RPC-based API?
para number - 4 and line number 3 

SOAP PRC ❌ => SOAP RPC ✅
![SOAP PRC](https://github.com/user-attachments/assets/009d6ece-ce6b-4741-936d-17222c3c2e5c)

**Comment by bsingha27** [comment]
Hi @osama0802, The README has been updated to reflect the erratum. We're closing this issue now.
