### ISSUE TITLE
DI field mismatch

### ISSUE THREAD

**Issue by osama0802** [PacktPublishing/Web-API-Development-with-ASP.NET-Core-8#2]
page number 68 

[HttpGet]
public async Task<ActionResult<List<Post>>> GetPosts()
{
var posts = await **_postService**.GetAllPosts();
return Ok(posts);
}

_postService ❌ _postsService✅
![DI Variable](https://github.com/user-attachments/assets/9af71e0c-8f7e-4923-aef1-5af1db91e59f)

**Comment by bsingha27** [comment]
@osama0802 The README has been updated to reflect the erratum. We're closing this issue now.
